apiVersion: v1
kind: Service
metadata:
  labels:
    app: appserver
  name: appserver
spec:
  type: LoadBalancer
  ports:
  - name: "appserver-service"
    port: 8081
    targetPort: 8081
  selector:
    app: appserver
